### ISSUE TITLE
Please add types

### ISSUE THREAD

**Issue by totoblabla3** [pier4all/mongoose-versioned#1]

**Comment by jcschmidig** [comment]
Hi, thanks for opening the issue and participating actively in the open source community. We welcome anyone willing to contribute to our projects. Would you mind to open a PR for your issue?

**Comment by jcschmidig** [comment]
I close this issue for not being responded. It may be reopened anytime if needed.

**Comment by totoblabla3** [comment]
clarify what it means to open PR?

**Comment by espona** [comment]
It means you contribute to this library by developing the improvement you suggested in your forked repository. Then you open a pull request (PR) and we can review your work and integrate it into our repository and publish a new version of the npm package for the community.  We thank you for your suggestion but adding types is not a priority for us right now.
