### ISSUE TITLE
Operation `identities.versioning.createIndex()` buffering timed out after 10000ms

### ISSUE THREAD

**Issue by r4wand** [pier4all/mongoose-versioned#10]
hey! thanks for the awesome library, been searching for one for a while.

I am trying to use this with Nestjs. It should be straightforward since it's just registering a plugin. but I am running into this issue.

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
MongooseError: Operation `identities.versioning.createIndex()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/nest/identity-api/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:151:23)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
```
here is how I register the plugin. which is basically the Nestjs way of registering a plugin.
```
import * as versioning from 'mongoose-versioned';
import mongoose from 'mongoose';

  MongooseModule.forFeatureAsync([
      {
        name: Identity.name,
        useFactory: () => {
          const schema = IdentitySchema;

          schema.plugin(versioning, {
            collection: 'identities.versioning',
            mongoose,
          });
          return schema;
        },
      },]
```

**Comment by r4wand** [comment]
I tried changing the collection name to `identities` and `identity` as one of the closed issues mention.  still doesn't work.

**Comment by espona** [comment]
I am not familiar with Nestjs, I below a code that should work, I hope you can adapt it.
Mongoose creates a collection with the plural form of the name you provide. The collections in Mongo will be called 'identities' and 'identities.versioning'.

```JavaScript
  // create the model
  let identitySchema = new Schema({
    name: { type: String, required: true, unique: false }
  })

  // add the versioning plugin to the schema and specify
  // the name of the shadow collection
  identitySchema.plugin(versioning, {collection:  "identities.versioning", mongoose})

  // instantiate the model
  let Identity = mongoose.model('identity', identitySchema)
```
Let me know if it works, if so I would appreciate if you include the snippet that works for future references.

**Comment by espona** [comment]
I hope you solved the issue, otherwise please reopen.

**Comment by achinth** [comment]
I am having the same issue. @r4wand can you please let me know the solution? I tried with both mongoose versions 6 and 7. Same issue with both when used with Nest.js
