### ISSUE TITLE
_editor and _deleter custom values

### ISSUE THREAD

**Issue by raghadzeidan** [pier4all/mongoose-versioned#4]
Hey! I would like to use mongoose-versioned for my project, yet i can't really find any documentation for non-basic use cases
i would like to store custom values in _editor and _deleter fields

**Comment by espona** [comment]
Hi, 

Thanks for your comment, we will try to improve the documentation.

I just added setting the editor to the example in the README, just need to set a field called "_editor" to the updated object information.
Do not specify this field in the object mongoose schema as it will be added to the schema by the plugin. You can specify the deletion information in a similar way.

Let me know if it works for you.

Best,
Lucia

**Comment by raghadzeidan** [comment]
Thanks for your response!
i was able to add the _editor information by passing the field to the update document, but where do I pass on the _deleter one? I am using a simple deleteOne function that takes a filter query - I could update and then delete but it seems wasteful, and it would place it in the _editor field and deleter is still default value

**Comment by raghadzeidan** [comment]
Update: I was able to achieve the mentioned above
ref:
<img width="826" alt="Screen Shot 2022-08-08 at 12 30 17" src="https://user-images.githubusercontent.com/57403348/183386781-49505c6e-d75a-4610-9ddc-4bfb1fa69465.png">

<img width="533" alt="Screen Shot 2022-08-08 at 12 42 28" src="https://user-images.githubusercontent.com/57403348/183389192-44e648d6-b842-460a-a2c0-74bcde324fe2.png">
