### ISSUE TITLE
Versioning of old documents

### ISSUE THREAD

**Issue by raghadzeidan** [pier4all/mongoose-versioned#5]
Hey! I am trying to integrate versioning into my already-existing collection, yet I am facing issues with posts they were previously there before introducing the plug in

When updating one of them, I get: `Error: modified and base versions do not match`
This is because version is missing from the origianl document, so by I adding `"_version" : 1` manually to the document, I bypass that and encounter `TypeError: Cannot read property 'start' of undefined`
adding 
```
"_validity" : {
        "start" : ISODate("2022-08-05T16:37:07.442Z")
    },
```
fixed this issue.

is there a way where I can take care of those legacy records, and not to have to manually update them to include version 1 and. start date? Maybe that will be a good enhancement, to treat old documents are version 0 with a startDate of the object time stamp or something.

Thanks!

**Comment by raghadzeidan** [comment]
Update: I have made the necessary changes for the above, I tested two cases:
1. Updating an already-existing record with no _version and _validity - WORKS
2. Delete an already-existing record with no _version and _validity - WORKS

default version will be saved in the shadow collection as 0, with the default start time being the object Id creation time.

though I'm unable to open a PR here to submit

**Comment by jcschmidig** [comment]
Hi, you should be able to create a PR. What does prevent you?

**Comment by jcschmidig** [comment]
Closed for no actions.

**Comment by ajmas** [comment]
I just ran into this issue with the error `modified and base versions do not match`, since we are adding this package to an existing project, with an existing collection.

Could the logic be adjusted, such that if an existing document does not have the `_version` property, then treat it as version 1?
